# NUMPY LIBRARY

In [1]:
import numpy as np
np.__version__
'1.21.5'

'1.21.5'

# CREATE A 1-D ARRAY USING array()

In [2]:
import numpy as np
a=np.array([1,2,3])
print(a)
print(a.dtype)
print(a.shape)

[1 2 3]
int32
(3,)


# Create A 1-D ARRAY USING arange()

In [4]:
import numpy as np
a=np.arange(3)
print(a)
print(a.dtype)
print(a.shape)

[0 1 2]
int32
(3,)


# CREATE A 2=D ARRAY USING array()

In [5]:
import numpy as np
b=np.array(([1,2,3],[4,5,6]))
print(b)
print(b.dtype)
print(b.shape)

[[1 2 3]
 [4 5 6]]
int32
(2, 3)


# CREATE A 2=D ARRAY USING arange()

In [6]:
import numpy as np
b=np.arange(10).reshape(2,5)
print(b)
print(b.dtype)
print(b.shape)

[[0 1 2 3 4]
 [5 6 7 8 9]]
int32
(2, 5)


In [7]:
import numpy as np
b=np.arange(10).reshape(5,2)
print(b)
print(b.dtype)
print(b.shape)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
int32
(5, 2)


# CREATE A 3-D ARRAY USING array()

In [8]:
import numpy as np
c=np.array(
        [
        [[1,2,3],[5,6,7]],
        [[8,9,10],[11,12,13]],
        [[14,15,16],[17,18,19]]
        ]
)
print(c)
print(c.dtype)
print(c.shape)

[[[ 1  2  3]
  [ 5  6  7]]

 [[ 8  9 10]
  [11 12 13]]

 [[14 15 16]
  [17 18 19]]]
int32
(3, 2, 3)


# CREATE A 3-D ARRAY USING arange()

In [11]:
import numpy as np
c=np.arange(1,19).reshape(3,3,2) 
print(c)
print(c.dtype)
print(c.shape)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]]
int32
(3, 3, 2)


# CREATE ARRAY OF ONES (1-D)

In [12]:
import numpy as np
d=np.ones(2,dtype=np.int32)
print(d)
print(d.dtype)
print(d.shape)

[1 1]
int32
(2,)


# CREATE ARRAY OF ONES(2-D)

In [1]:
import numpy as np
d=np.ones((2,3),dtype=np.int32)
print(d)
print(d.dtype)
print(d.shape)

[[1 1 1]
 [1 1 1]]
int32
(2, 3)


# CREATE ARRAY OF ONES(3-D)

In [2]:
import numpy as np
d=np.ones((3,2,3),dtype="int32")
print(d)
print(d.dtype)
print(d.shape)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]
int32
(3, 2, 3)


# CREATE ARRAY OF ZEROS(1-D)

In [3]:
import numpy as np
f=np.zeros((3),dtype=np.int32)
print(f)
print(f.dtype)
print(f.shape)

[0 0 0]
int32
(3,)


# CREATE ARRAY OF ZEROS(2-D)

In [4]:
import numpy as np
f=np.zeros((2,3),dtype=np.int32)
print(f)
print(f.dtype)
print(f.shape)

[[0 0 0]
 [0 0 0]]
int32
(2, 3)


# CREATE ARRAY OF ZEROS(3-D)

In [5]:
import numpy as np
f=np.zeros((3,2,3),dtype=np.int32)
print(f)
print(f.dtype)
print(f.shape)

[[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]]
int32
(3, 2, 3)


# CREATE AN ARRAY WITH RANDOM NUMBERS(1-D)

In [6]:
import numpy as np
a=np.random.randint(1,6,size=(6))
print(a)
print(a.dtype)
print(a.shape)

[1 1 2 3 1 3]
int32
(6,)


# CREATE AN ARRAY WITH RANDOM NUMBERS(2-D)

In [7]:
import numpy as np
b=np.random.randint(1,11,size=(2,3))
print(b)
print(b.dtype)
print(b.shape)

[[ 6  2  8]
 [ 3  2 10]]
int32
(2, 3)


# CREATE AN ARRAY WITH RANDOM NUMBERS(3-D)

In [8]:
import numpy as np
c=np.random.randint(10,21,size=(3,2,3))
print(c)
print(c.dtype)
print(c.shape)

[[[20 19 17]
  [15 18 10]]

 [[20 12 16]
  [19 17 15]]

 [[19 11 11]
  [20 18 14]]]
int32
(3, 2, 3)


# CREATE ARRAY WITH SINGLE LOW MULTIPLE HIGH

In [9]:
import numpy as np
a=np.random.randint(5,[10,20,30])
print(a)
print(a.dtype)
print(a.shape)

[ 6 19 24]
int32
(3,)


# CREATE ARRAY WITH MULTIPLE LOW SINGLE HIGH

In [10]:
import numpy as np
b=np.random.randint([1,2,3],10)
print(b)
print(b.dtype)
print(b.shape)

[7 5 7]
int32
(3,)


# CREATE ARRAY WITH MULTIPLE LOW MULTIPLE HIGH

In [11]:
import numpy as np
b=np.random.randint([1,2,3,5],[10,20,30,40])
print(a)
print(a.dtype)
print(a.shape)

[ 6 19 24]
int32
(3,)


# CREATE ARRAY WITH RANDOM NUMBERS USING random()(1-D)

In [12]:
import numpy as np
a=np.random.rand(5)
print(a)
print(a.dtype)
print(a.shape)

[0.86831305 0.47522353 0.94823554 0.14821312 0.16415614]
float64
(5,)


# CREATE NUMPY WITH RANDOM NUMBERS USING random() (2-D)

In [13]:
import numpy as np
b=np.random.randn(3,2)
print(b)
print(b.dtype)
print(b.shape)

[[-0.64341059  0.07383063]
 [-0.28692763  1.62936818]
 [-0.43966843 -0.74049551]]
float64
(3, 2)


# CREATE ARRAY WITH RANDOM NUMBERS USING randn() (3-D)

In [14]:
import numpy as np
c=np.random.randn(3,3,2)
print(c)
print(c.dtype)
print(c.shape)

[[[ 1.12730467 -0.90574636]
  [-0.74907263  0.03676599]
  [-0.28884888 -0.31987602]]

 [[-0.00214744 -1.03102747]
  [ 0.90596327  0.02697542]
  [-0.58359079 -0.19650718]]

 [[ 0.79558909 -0.42069816]
  [-1.30362721  1.46150766]
  [ 0.03597108  1.08395228]]]
float64
(3, 3, 2)


# CREATE ARRAY OF RANDOM NUMBERS USING rand()

In [15]:
import numpy as np
a=np.random.rand(5)
print(a)
print(a.dtype)
print(a.shape)

[0.71846777 0.11073105 0.15407341 0.54310495 0.67096559]
float64
(5,)


# POSITIVE INDEXING IN ARRAY(left-right)

In [16]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8])
print(arr[2])
print(arr[7])
arr[3]

3
8


4

In [17]:
import numpy as np
arr=np.array([[1,2,3],[5,6,7],[8,9,10]])
print(arr[0,2])
print(arr[1,1])
print(arr[1,0])
print(arr[2,1])

3
6
5
9


In [18]:
#array with 3-D
import numpy as np
arr=np.array(
    [
        [[1,2,3],[4,5,6]],
        [[10,20,30],[12,13,14]],
        [[100,200,300],[400,500,600]]    
    ]
            )
print(arr[0,1,1])
print(arr[2,1,0])
print(arr[1,1,1])

5
400
13


# NEGETIVE INDEXING IN ARRAY(right - left)

In [19]:
#array with 1-D
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[-2])
print(arr[-1])
print(arr[-7])

6
7
1


In [20]:
#array with 2-D
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr[-1,-2])
print(arr[-2,-1])

5
3


# MIXING OF (+ AND -)

In [21]:
import numpy as np
arr=np.array(
    [
        [[2,3,4],[5,6,7]],
        [[10,2,4],[6,7,29]],
        [[22,11,14],[23,45,44]]
    ]
)
print(arr[1,1,1])
print(arr[-2,-1,-2])
print(arr[2,-1,2])
print(arr[-1,1,-2])

7
7
44
45


# NUMPY ARRAY SLICING

In [22]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[1:5])

[2 3 4 5]


In [24]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr[4:])

[5 6 7 8 9]


In [25]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[:4])

[1 2 3 4]


# NEGETIVE SLICING

In [27]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[-3:-1])
print(arr[-6:-2])

[5 6]
[2 3 4 5]


In [28]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[1:5:2])

[2 4]


In [29]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[::2])

[1 3 5 7]


# SLICING 2-D ARRAYS

In [30]:

import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,1:4])

[7 8 9]


In [31]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2,2])

[3 8]


In [32]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2,1:4])

[[2 3 4]
 [7 8 9]]


# NUMPY ARRAY COPY VS VIEW

In [1]:
import numpy as np
arr = np.array([1,2,3,4,5])
a = arr.copy()
print("original array")
print(arr)
print("affected array")
arr[2] = 10
print(arr)
print(a)


original array
[1 2 3 4 5]
affected array
[ 1  2 10  4  5]
[1 2 3 4 5]


In [2]:
import numpy as np
arr = np.array([1,2,3,4,5])
x = arr.view()
print("original array")
print(arr)
print("viewed array")
print(x)
print("affected array")
arr[0] = 30
print("arr : ",arr)
print(" x :",x)

original array
[1 2 3 4 5]
viewed array
[1 2 3 4 5]
affected array
arr :  [30  2  3  4  5]
 x : [30  2  3  4  5]


# reshape() FUNCTION

In [3]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print("original array :",arr) #1d

original array : [ 1  2  3  4  5  6  7  8  9 10]


In [4]:
#2D ARRAY
b = arr.reshape(5,2) 
print("2D array with shape 5x2")
print(b)
c = arr.reshape(2,5) 
print("2D array with shape 2x5")
print(c)

2D array with shape 5x2
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
2D array with shape 2x5
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [5]:
#3D ARRAY 
d = arr.reshape(2,1,5)
print("3D array with shape 2,1,5")
print(d)

3D array with shape 2,1,5
[[[ 1  2  3  4  5]]

 [[ 6  7  8  9 10]]]


# AGREEGATION FUNCTIONS
sum() FUNCTION

In [6]:
import numpy as np
arr=np.array([1,2,3,4,5]) #1D
print("original 1D array : ",arr)
print(f"sum={np.sum(arr)}")
print()

original 1D array :  [1 2 3 4 5]
sum=15



In [7]:
arr1=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("original 2D array : ",arr1)
print(f"sum={np.sum(arr1)}")
print()

original 2D array :  [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
sum=55



In [8]:
arr2=np.array(
              [
               [[1,2,3],[4,5,6]],
               [[10,20,30],[40,50,60]]    
              ]
             )
print("original 3D array : ",arr2)
print(f"sum={np.sum(arr2)}")  


original 3D array :  [[[ 1  2  3]
  [ 4  5  6]]

 [[10 20 30]
  [40 50 60]]]
sum=231


In [9]:
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]])
print("original array \n:",arr)
print("Across Colswise") #column wise
print("sum =",np.sum(arr , axis=0))
print("Across Rowswise") #Row wise
print("sum =",np.sum(arr , axis=1))


original array 
: [[1 2 3 4]
 [5 6 7 8]]
Across Colswise
sum = [ 6  8 10 12]
Across Rowswise
sum = [10 26]


# mean() FUNCTION

In [10]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8])
print("original array : ",arr)
print("mean : ",np.mean(arr)) 

original array :  [1 2 3 4 5 6 7 8]
mean :  4.5


In [11]:
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]])
print("original array \n: ",arr)
print("Across Rows") #column wise
print("Mean =",np.mean(arr , axis=0))
print("Across Columns") #Row wise
print("Mean =",np.mean(arr , axis=1))

original array 
:  [[1 2 3 4]
 [5 6 7 8]]
Across Rows
Mean = [3. 4. 5. 6.]
Across Columns
Mean = [2.5 6.5]


# std() FUNCTION

In [12]:
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]])
print("original array : ",arr)
print()
print("standard div : ",np.std(arr)) 

original array :  [[1 2 3 4]
 [5 6 7 8]]

standard div :  2.29128784747792


In [13]:
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]])
print("original array : ",arr)
print("Across Rows") #column wise
print("std div =",np.std(arr , axis=0))
print()
print("Across Columns") #Row wise
print("std div =",np.std(arr , axis=1))

original array :  [[1 2 3 4]
 [5 6 7 8]]
Across Rows
std div = [2. 2. 2. 2.]

Across Columns
std div = [1.11803399 1.11803399]


# var() FUNCTION

In [14]:
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]])
print("original array : ",arr)
print()
print("varients : ",np.var(arr)) 

original array :  [[1 2 3 4]
 [5 6 7 8]]

varients :  5.25


In [15]:
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]])
print("original array : ",arr)
print("Across Rows") #column wise
print("var =",np.var(arr , axis=0))
print()
print("Across Columns") #Row wise
print("var =",np.var(arr , axis=1))

original array :  [[1 2 3 4]
 [5 6 7 8]]
Across Rows
var = [4. 4. 4. 4.]

Across Columns
var = [1.25 1.25]


# min() FUNCTION

In [16]:
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]])
print("original array : ",arr)
print()
print("minimum : ",np.min(arr)) 

original array :  [[1 2 3 4]
 [5 6 7 8]]

minimum :  1


In [17]:
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]])
print("original array : ",arr)
print("Across Rows") #column wise
print("min =",np.min(arr , axis=0))
print()
print("Across Columns") #Row wise
print("min =",np.min(arr , axis=1))

original array :  [[1 2 3 4]
 [5 6 7 8]]
Across Rows
min = [1 2 3 4]

Across Columns
min = [1 5]


# max() FUNCTION

In [18]:
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]])
print("original array : ",arr)
print()
print("maximum : ",np.max(arr)) 

original array :  [[1 2 3 4]
 [5 6 7 8]]

maximum :  8


In [19]:

import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]])
print("original array : ",arr)
print("Across Rows") #column wise
print("max =",np.max(arr , axis=0))
print()
print("Across Columns") #Row wise
print("max =",np.max(arr , axis=1))

original array :  [[1 2 3 4]
 [5 6 7 8]]
Across Rows
max = [5 6 7 8]

Across Columns
max = [4 8]
